//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_BBSItem
    {
        public Table_BBSItem()
        {
            this.Table_BBSManager = new HashSet<Table_BBSManager>();
            this.Table_Question = new HashSet<Table_Question>();
        }
    
        public System.Guid ID { get; set; }
        public string BBSTypeName { get; set; }
    
        public virtual ICollection<Table_BBSManager> Table_BBSManager { get; set; }
        public virtual ICollection<Table_Question> Table_Question { get; set; }
    }
}
