//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_BBSManager
    {
        public int Id { get; set; }
        public System.Guid BBSTypeId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Table_BBSItem Table_BBSItem { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
