//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_BlogReply
    {
        public Table_BlogReply()
        {
            this.Table_SubBlogReply = new HashSet<Table_SubBlogReply>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid BlogID { get; set; }
        public string Content { get; set; }
        public System.Guid Publisher { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Table_Blog Table_Blog { get; set; }
        public virtual Table_User Table_User { get; set; }
        public virtual ICollection<Table_SubBlogReply> Table_SubBlogReply { get; set; }
    }
}
